### ISSUE TITLE
Apple Music / Mute button not respected on track change

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#10]
<img width="141" alt="image" src="https://user-images.githubusercontent.com/161305/113478739-11818d00-948b-11eb-9ad8-1d3190a83eb0.png">

This button mutes the music, but when the next track starts sounds is back even when the label shows muted

**Comment by t3dotgg** [comment]
Ooof yeah this is due to the fake mute I'm doing with the skim, good catch. Will have to make something more robust

**Comment by t3dotgg** [comment]
Fixed :)
