### ISSUE TITLE
No spotify URI for this track

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#13]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/161305/113552184-1151d080-95f6-11eb-907a-58ec26f6ad3f.png">

Is the search still using apple music?

**Comment by t3dotgg** [comment]
Yes search is still using apple for now. We're going to do matching with a 3rd party so the isrc match doesn't break as often

**Comment by francisdb** [comment]
At least I can listen using Firefox now!

**Comment by t3dotgg** [comment]
Just pushed changes to fix this, we now fall back on odesli.co when I can't find a spotify URI via ISRC

**Comment by francisdb** [comment]
let's close this one for now
