### ISSUE TITLE
Can't play after I have left the dj spot

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#14]
Firefox 87.0 (64-bit)

1. Play music
2. Leave
3. You end up with below state

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/161305/113560716-bb842500-9603-11eb-86bf-0314a49b7b01.png">

**Comment by fasm** [comment]
The same thing can occur in MacOS // Brave Version 1.22.71

**Comment by t3dotgg** [comment]
Fixed :)
