### ISSUE TITLE
Spotify - The access token expired

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#17]
Entered a room but no music playing (tab was open for a while)

fixed with CMR-SHIFT-R

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/161305/113890713-b0c4be00-97c4-11eb-8b4d-f9fe11158c20.png">

**Comment by t3dotgg** [comment]
80% sure I fixed this, re-open if I'm wrong
