### ISSUE TITLE
Chat does not scroll to last line when entering room

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#18]
It only scrolls down after somebody says something

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/161305/113891196-22047100-97c5-11eb-89b4-3a377c3eac57.png">

**Comment by rosexi** [comment]
We've fixed this and should be live soon! (Snowy PR#161)

**Comment by t3dotgg** [comment]
Fix'd
