### ISSUE TITLE
Spotify - not all playlists listed

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#19]
I have I think about 50+ playlists, only part of that is listed

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/161305/114156283-acaeb280-9922-11eb-8ae0-380920bdc8c6.png">

**Comment by francisdb** [comment]
A filter/search might help ui-wise

**Comment by t3dotgg** [comment]
Raised cap to 50 for now, which should cover most users. I have a slightly lower priority ticket to add pagination:
https://trello.com/c/0FZbQpMm/52-add-pagination-for-playlist-search-and-playlist-tracks

**Comment by francisdb** [comment]
Looks likelooks like the ordering is preserved so some reordering in spotify also helps here
