### ISSUE TITLE
Apple music account link broken on firefox

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#4]
Firefox 87.0 (64-bit)
Tested from EU/Belgium
I can't get the apple music link to work

After 2fa check with code I end up with this

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/161305/113398206-8034ec80-939e-11eb-81d8-fccd0f601831.png">

**Comment by francisdb** [comment]
Would be good if somebody could confirm this

**Comment by t3dotgg** [comment]
I was able to consistently hit that white screen Apple auth bug while VPNing to Belgium in both Chrome and Safari. Not sure if this is FF specific. CC @Andrewjeska

**Comment by t3dotgg** [comment]
Unable to replicate w/o belgium VPN. Everything's working surprisingly good for me in FF
![image](https://user-images.githubusercontent.com/6751787/113492269-26f6b700-948b-11eb-941f-b916a9b4e59e.png)

**Comment by t3dotgg** [comment]
Weird. Started working on dev (localhost) and it failed the same was as you showed above
![image](https://user-images.githubusercontent.com/6751787/113492337-82c14000-948b-11eb-8d71-33d6d2edd11b.png)

Worked on refresh

**Comment by t3dotgg** [comment]
Did notice some audio issues on initial load, this seemed to fix:
![image](https://user-images.githubusercontent.com/6751787/113492385-d5026100-948b-11eb-88c6-57b07effeaf2.png)

**Comment by t3dotgg** [comment]
Should be fixed now - issue was that firefox expected it to be an `<a />` element lol
