### ISSUE TITLE
MusicKit JS playback fails after ~15 minutes

### ISSUE THREAD

**Issue by t3dotgg** [TTFM-Labs/public#7]
Apple Music playback consistently fails after 15 minutes of activity.

The only event I've managed to sniff is a state change from "2" to "8".

### Logs
I fetched the musickit instance and tried to manually force play to resume. All of the promises hung
![image](https://user-images.githubusercontent.com/6751787/113464283-53092e00-93e0-11eb-8756-40406748127a.png)

### Related issues
https://developer.apple.com/forums/thread/120822
https://developer.apple.com/forums/thread/665141
https://github.com/Musish/Musish/issues/315

**Comment by t3dotgg** [comment]
Cut an issue on Apple's forums
https://developer.apple.com/forums/thread/677379

**Comment by t3dotgg** [comment]
Likely related

![image](https://user-images.githubusercontent.com/6751787/113466163-70dd8f80-93ee-11eb-92f6-2f78d7e153e8.png)

**Comment by t3dotgg** [comment]
Was able to make an awful temporary fix of creating a new instance via `MusicKit.configure()` every track play

**Comment by t3dotgg** [comment]
I deobfuscated the MusicKit.js file to prod around a bit. Looks like the failing update is part of the `widevine` implementation on Chrome. Also noticed it seems to work fine on Safari

```js
        (KeySession.prototype._handleLicenseResponse = function (
          currentLicense,
          keySesh,
          bigToken,
        ) {
          var i = this;
          if (currentLicense.license) {
            currentLicense["renew-after"] &&
              (this._pendingRenewal = setTimeout(function () {
                console.log("What is i", i);
                console.log("URL", i.extURI);
                i.acquirePlaybackLicense(i.extURI, bigToken).then(function (e) {
                  console.log("just acquired maybe", e);
                  i._handleLicenseResponse(e, keySesh, bigToken);
                });
              }, 8000));
            var n = $e(currentLicense.license);
            console.log("using keySesh for updating?", keySesh);
            console.info("\n\n\n NEW LICENSE", n);
            try {
              return keySesh.update(n); // This is the call that tries to update WIdevine's encryption key. Passes first time, fails afterwards
            } catch (fail) {
              console.error("FAILED", fail);
            }
          }
          var o = ee.serverError(currentLicense);
          if (this.initiated) throw o;
          this.dispatchEvent(or.playbackLicenseError, o);
        }),
```

**Comment by t3dotgg** [comment]
Update part 2: Safari works because it uses fairplay not widevine

I'm pretty sure this is the native function being called that is failing. Likely due to being passed a semi-invalid key:
https://github.com/WebPlatformForEmbedded/OCDM-Widevine/blob/master/MediaSession.cpp#L204

**Comment by t3dotgg** [comment]
Same error occurs in a Google player app using widevine. Appears to be an issue with the configuration of the server that generates the tokens on Apple's behalf https://github.com/google/shaka-player/issues/2702

**Comment by shimondoodkin** [comment]
I think Apple changed the expiration time to song time + 10 minutes of license request, it means, need to discard songs played and request license again, it means you cant preload songs

**Comment by marstall** [comment]
i had a developer lab session at wwdc 2021 with 2 musickitjs engineers and asked about this issue. they actually have been working diligently on it and shared a link with me to a v3 musickitjs beta release. i've been using it in in my app and it definitely solves this issue for me. I had been expecting some kind of announcement or discussion of it, but haven't seen it yet.

I am tempted to just post the link here but as it was shared privately with me I'm worried it will be withdrawn if it's publicly posted, or something. 

On the other hand I know many are kneecapped by this issue and I'd like to help. What should I do?

**Comment by t3dotgg** [comment]
> i had a developer lab session at wwdc 2021 with 2 musickitjs engineers and asked about this issue. they actually have been working diligently on it and shared a link with me to a v3 musickitjs beta release. i've been using it in in my app and it definitely solves this issue for me. I had been expecting some kind of announcement or discussion of it, but haven't seen it yet.
> 
> 
> 
> I am tempted to just post the link here but as it was shared privately with me I'm worried it will be withdrawn if it's publicly posted, or something. 
> 
> 
> 
> On the other hand I know many are kneecapped by this issue and I'd like to help. What should I do?

I found it myself last week lol. They've deleted about half the public documentation since. Scared to give it a try myself but knowing you've had good luck I may give it a go

https://js-cdn.music.apple.com/musickit/v3/docs/index.html

**Comment by marstall** [comment]
nice! how did you find it? I was looking everywhere previously.

**Comment by shimondoodkin** [comment]
i have made this one
https://gist.github.com/shimondoodkin/edfb5438987ed672a3d5e7dc356181cf

it recreates session before each track
it catches error
if session crashes inside a long track, it recreates session and resumes same place 
it does not change any player html tags so derived stream objects remain same

it is apple v1 script with bugs fixed

**Comment by marstall** [comment]
@shimondoodkin that looks interesting and those sound like needed features! would be curious to hear more, and maybe an example of how to use it?

**Comment by shimondoodkin** [comment]
just instead of taking the js from apple's site, put this on your site, and use it.
it is apple's script unminified with bugs fixed.


```


<!-- script src="https://js-cdn.music.apple.com/musickit/v1/musickit.js" script -->
<script src="%PUBLIC_URL%/applemusic.js" type="text/javascript"></script>

<script>
// Valid for only 180 days. today is: 15151212020 expieres at: 151512020
const developerToken = `fskgdjfrkoasdfjkadnxlkd...`;
const { MusicKit } = window;

  const loadAppleMusic = async () => {
    const appleMusic = MusicKit.configure({
      developerToken,
      app: {
        name: 'yourname here',
      },
    });
    await appleMusic.authorize();

    return appleMusic;
  };

</script>


```

**Comment by Behinder** [comment]
> i had a developer lab session at wwdc 2021 with 2 musickitjs engineers and asked about this issue. they actually have been working diligently on it and shared a link with me to a v3 musickitjs beta release. i've been using it in in my app and it definitely solves this issue for me. I had been expecting some kind of announcement or discussion of it, but haven't seen it yet.
> 
> I am tempted to just post the link here but as it was shared privately with me I'm worried it will be withdrawn if it's publicly posted, or something.
> 
> On the other hand I know many are kneecapped by this issue and I'd like to help. What should I do?

How can it work for you, I cannot use MusicKit v3 with Apple own code example because "await" keyword not work in the browser withous async and you cannot put async anywhere in document.addEventListener? That made me switch to v1 and I confirm on Chrome error stil appears.

**Comment by marstall** [comment]
@Behinder can you post your code here? happy to take a look

**Comment by Behinder** [comment]
@marstall sure, damn I deleted all projectfrom the frustration  after that but it was from Apple docs:
````
document.addEventListener('musickitloaded', function () {
  // MusicKit global is now defined.

  // Call configure() to configure an instance of MusicKit JS.
  await MusicKit.configure({
    developerToken: 'DEVELOPER-TOKEN',
    app: {
      name: 'My Cool Web App',
      build: '1978.4.1',
    },
  }).then(function (instance) {
    // MusicKit instance is available.
  });
});
````
that itself is not possible to work because await not run without async and you cannot do async in callbak

**Comment by t3dotgg** [comment]
Closing this because v3 solved it - I don't think this is the beset place for further discussion

**Comment by shimondoodkin** [comment]
see 
https://js-cdn.music.apple.com/musickit/v3/docs/index.html

**Comment by Behinder** [comment]
v3 not solved anything because it's in beta still and not work in browser
with Apple example code.

**Comment by marstall** [comment]
@Behinder this is how I do it, hope it helps ...

```
async function setupMK()  {
    try {
      window.MusicKitInstance = await window.MusicKit.configure({
        bitrate: window.MusicKit.PlaybackBitrate.HIGH,
        developerToken,
        app: {
          name: "byname",
          build: "1"
        }
      });
    } catch (e) {
      console.log(e.message);
      window.alert("Error initializing apple music: "+e.message);
      return;
    }
}

document.addEventListener('musickitloaded', setupMK);
```

**Comment by Behinder** [comment]
Thanks, I'll check it out somehow I have impression that won't work on my machine ;) 
this is weird but if your code works also this construct
````
document.addEventListener('musickitloaded', async function() {});
```` 
should but it's not. Also the problem with your code I see is you have only this one function in this listener. You cannot perform any Apple Music related stuff if setupMK is not first configured so how do you ensure other code launch after that? Do you use perhaps Promise.All()?

**Comment by marstall** [comment]
you could do this:
```
async function setupMK()  {
    try {
      window.MusicKitInstance = await window.MusicKit.configure({
        bitrate: window.MusicKit.PlaybackBitrate.HIGH,
        developerToken,
        app: {
          name: "byname",
          build: "1"
        }
      });
      const musicUserToken = await window.MusicKitInstance.authorize()
      // now you're ready to do Apple Music stuff or update global state (eg w/ redux, react context, etc) with musicUserToken
      // so other modules can know its ok to start doing Apple Music stuff 
    } catch (e) {
      console.log(e.message);
      window.alert("Error initializing apple music: "+e.message);
      return;
    }
}

document.addEventListener('musickitloaded', setupMK);
```

**Comment by marstall** [comment]
btw I don't know if you're a book person but I got a lot out of this book when I was trying to level up my knowledge from "regular" js to es6 https://www.thriftbooks.com/w/you-dont-know-js-es6--beyond_kyle-simpson/11436481/item/18378389/?gclid=CjwKCAiAtdGNBhAmEiwAWxGcUgKCuDAovDzXvdupiTVGCQ-6AqFTPlh-bgnogILifRmkUHf8VlmSxRoC7l4QAvD_BwE#idiq=18378389&edition=10966143

**Comment by Behinder** [comment]
Thanks I usually rely on tutorials, books can become quickly outdated. I found the issue.
Looks Apple code is wrong because async await syntax in top scope is supported in Safari 15 and I am using 14.1. I filled the bug to Apple it's unacceptable to leave people on older systems and not update their own browser which is lame. Anyway I stick with v1. Thanks for replying.

**Comment by marstall** [comment]
Ah. Presumed you were using babel. Best of luck.

**Comment by Behinder** [comment]
Thanks, I think I abandon the project. Too much non-debuggable errors.

**Comment by Behinder** [comment]
Also, I filled bug to Apple via Feedback Assistant asking them to remove promise from configure and bring back old proper behavior. The proposed one will create callback hell.
